//1. comments can make code Readable

//2. Welcome to 30DaysOfJavascript

/*3. comments can make code readable,
easy to reuse and informative*/

//4. Create a variable.js file and declare variables and assign string, boolean, undefined and null data types

let a = "bayo";
let b = true;
let c;
let d = null;

//5. Create datatypes.js file and use the JavaScript typeof operator to check different data types. Check the data type of each variable

let e = "deji";
let f = false;
let g;
let h = null;

console.log(typeof e);
console.log(typeof f);
console.log(typeof g);
console.log(typeof h);

//6. Declare four variables without assigning values

let i;
let j;
let k;
let l;

//7. Declare four variables with assigned values

let name = "ola";
let age = 30;
let gender = "male";
let ismarried = false;

//8. Declare variables to store your first name, last name, marital status, country and age in multiple lines

//let firstname;
//let lastname;
//let marital status;
//let country;
//let age;

//9. Declare variables to store your first name, last name, marital status, country and age in a single line

//let firstname, lastname, marital status, country, age;

//10. Declare two variables myAge and yourAge and assign them initial values and log to the browser console.

let myAge = 40;
let yourAge = 50;
console.log("I am ", myAge, " years old");
console.log("You are " + yourAge + " years old");
